[package]
name = "flowfield_particules"
version = "0.1.0"
authors = ["Alexis CARE <alx.care@gmail.com>"]
edition = "2018"

[dependencies]
noise = "0.5.1"
sdl2 = "0.32.1"
rand = "0.6.5"
arr_macro = "0.1.0"
euclid = "0.19.7"
crossbeam = "0.7.1"